#mulanbay配置
mulanbay:
  #节点编号(应用场景：调度)
  nodeId: mulanbay_node
  version: 5.0.0
  #命名空间，主要是缓存使用
  namespace: mulanbay
  score:
    #用户默认评分
    default: 60
    #评分统计周期
    statDays: 30
    #评分的缓存时间(秒)
    cacheTime: 300
  picture:
    #图片路径（头像使用）
    baseUrl: http://localhost:99/avatar
    #本地存放文件夹地址
    folder: ./picture
  #备份
  backup:
    #备份文件存放路径
    filePath: /mulanbay/server/backup
  mobile:
    #移动端根地址
    baseUrl: http://localhost:81/
  #线程池
  threadPool:
    corePoolSize: 20
    queueSize: 1024
    maximumPoolSize: 200
  cache:
    bean:
      #通用bean的失效时间(秒)
      expires: 300
    config:
      #缓存配置是否采用内存(false表示用redis)
      byMemory: false
  #持久层列表查询缓存
  persistent:
    page:
      #最大的每页数量
      maxPageSize: 20
      cache:
        #缓存前缀
        keyPrefix: pageSearch
        #列表数据是否缓存
        list : false
        #总记录值是否缓存
        total : false
        #需要缓存的bean，多个以英文逗号分隔，如果是全部则直接用* 表示
        beans: SysLog,OperLog
        #缓存时长
        expireSeconds: 10
  #安全相关
  security:
    lock:
      #系统状态解锁码位数
      unlockRandoms: 6
      #白名单
      whiteList:
        - /system/unlock
        - /captcha/captchaImage
    #图形验证码
    captcha:
      #类型
      type: math
      #失效时间(秒)
      expires: 300
    login:
      # 登录是否需要持久
      persist: true
      # 最大失败次数
      maxFail: 5
    password:
      #MD5密码的盐值
      salt: mysalt
    # token配置
    token:
      # 令牌取值位置:header / cookie
      way: header
      # 令牌自定义标识
      header: Authorization
      # 令牌密钥
      secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
      # 令牌有效期（默认30分钟）
      expireTime: 1800
      # 验证令牌有效期（默认20分钟）
      verifyTime: 1200
  log:
    #是否记录系统日志
    sysLog: true
    #是否记录操作日志
    operLog: true
  notify:
    message:
      #是否重启时清空队列中的消息
      clearAfterRestart: false
      #期望发送时间
      expectSendTime: 09:00
      #是否需要提醒表单验证类的错误代码
      validateError: false
      #大于该天数的不再发送
      expiredDays: 3
      send:
        #消息最大发送失败次数
        maxFail: 3
        #每次发送失败重试次数
        retryTimes: 3
        #消息发送是否需要锁定
        lock: true
        #是否同步发送
        sync: true
    code:
      #系统代码次数批量更新点
      batchUpdates: 20
  #调度相关
  schedule:
    #是否开启调度服务
    enable: false
    #是否支持分布式
    distriable: true
    #分布式任务最小的花费时间(毫秒)
    distriTaskMinCost: 2000
    #调度触发器检查周期(秒),<=0不检查
    monitorInterval: 60
    #调度服务器关闭时停止等待时间
    shutDownWaitSeconds: 5
    #花费时间计算方式（取值类型：AVG,MIN,MAX,LAST）
    costTimeCalcType: MAX
    #花费时间计算天数
    costTimeDays: 7
    #花费时间比例
    costTimeRate: 1.2
    #锁
    lock:
      #重试次数
      retryTimes: 3
    #线程池
    threadPool:
      corePoolSize: 20
      queueSize: 1024
      maximumPoolSize: 200
  #微信相关
  wx:
    #公众号ID
    appId: < set in local properties>
    secret: < set in local properties>
    token: < set in local properties>
    #授权回调地址
    accessAuthRedirectUrl: < set in local properties>
    #消息模版编号
    msgTemplateId: < set in local properties>
    #公众号地址
    oaUrl: < set in local properties>
    #公众号图片地址(移动端使用)
    oaPicUrl: < set in local properties>
  #消费相关
  consume:
    stat:
      #商品类型分组时是否以顶层分组
      groupTop: true
    tag:
      #历史tag统计天数
      statDays: 365
      num: 5
    cacheQueue:
      #缓存中的队列失效时间(智能匹配使用)
      expireDays: 7
      size: 100
    match:
      #NLP匹配时的最高匹配度，高于这个数不再往下匹配
      maxDegree: 0.8
      #NLP匹配时的最低匹配度，低于这个数认为没有匹配到
      minDegree: 0.4
      #商品类型的匹配列表过期时间(秒)
      goodsTypeExpireTime: 3600
      #匹配追踪有效时长(秒)
      traceExpires: 180
      #参与比较的关键字数
      tag: 3
  sport:
    #最大的基准心率
    maxHeartRate: 220
  health:
    #分类分组的时长
    categoryDays: 365
    drug:
      #用药的最小间隔（分钟）
      detailMinInv: 30
  food:
    cate:
      #分类的统计天数
      days: 14
      #缓存失效时间
      expireTime: 3600
      #NLP匹配时的最高匹配度，高于这个数不再往下匹配
      maxDegree: 0.85
      #NLP匹配时的最低匹配度，低于这个数认为没有匹配到
      minDegree: 0.1
  experience:
    mapStat:
      #地图统计使用字段，出发城市或者抵达,值：start / arrive
      field: arrive
      #明细统计时时间格式化
      dateFormat: yyyy
  businessTrip:
    mapStat:
      #明细统计时时间格式化
      dateFormat: yyyy
  commonData:
    #分类分组的时长
    categoryDays: 90
  behavior:
    tag:
      #词语统计时的分词数
      num: 5
  user:
    level:
      #用户级别评定统计间隔区间天数
      judgeDays: 30
  nlp:
    model:
      #模型是否要初始化
      init: false
  report:
    userStat:
      #统计的超时时间，主要是首页统计使用
      expires: 3600
  ml:
    #机器学习模型文件
    pmml:
      modelPath: /mulanbay/server/pmml
      verify: false
      initModel: true

# hibernate相关
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: false

spring:
  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pms?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      #    password: 123456 #默认为空
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20  # 最大连接数，负值表示没有限制，默认8
          max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
          max-idle: 8     # 最大空闲连接，默认8
          min-idle: 0     # 最小空闲连接，默认0
  #jsckson
  jackson:
    # 解决spring json解析相差8个小时的时区问题（针对POST方法，且时间为yyyy-MM-dd模式）
    time-zone: GMT+8
  #加载本地配置文件
  profiles:
    include: local
  servlet:
    #文件上传限制
    multipart:
      max-file-size: 50MB
      max-request-size: 1024MB
  mail:
    #发送邮件的邮箱地址：改成自己的邮箱
    username: < set in local properties>
    #qq邮箱采用授权码发送，非邮箱密码
    password: < set in local properties>
    ##平台地址，这里用的是qq邮箱，使用其他邮箱请更换
    host: smtp.qq.com
    port: 587
    #与发件邮箱一致
    from: < set in local properties>


#服务
server:
  servlet:
    #启动项目名
    context-path: /api
  ##配置tomcat端口，针对内置的tomcat
  port: 8080
  #绑定ip地址,只能由设置的地址进入访问
  address: 127.0.0.1
  tomcat:
    threads:
      max: 500
      min-spare: 100
